import type { Metadata } from "next";
import { Geist, Rubik_Glitch, Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header";
import { ThemeProvider } from "next-themes";
import AppLoader from "@/hoc/AppLoader";

const main = Geist({
  variable: "--font-main",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  weight: ['900'],
  subsets: ["latin"],
});

const glitch = Rubik_Glitch({
  variable: "--font-titles",
  weight: ['400'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="h-full" suppressHydrationWarning>
      <body
        className={`${rubik.variable} ${main.variable} ${glitch.variable} h-full antialiased`}
      >
        <AppLoader>
          <Header />
          <ThemeProvider
            attribute='class'
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <main className="h-[500vh]">
              {children}
            </main>
          </ThemeProvider>
        </AppLoader>
      </body>
    </html>
  );
}
